use("modelWideColumn");

db.dropDatabase();

db.orders.insertMany([
  {
    _id: ObjectId("60a7c9c9c9c9c9c9c9c9c9c1"),
    order_id: "ORD001",
    customer_info: {
      customer_id: "CUST001",
      name: "Ahmad Rizki",
      email: "ahmad.rizki@email.com",
      phone: "081234567890",
    },
    shipping_address: {
      street: "Jl. Sudirman No. 123",
      city: "Jakarta",
      province: "DKI Jakarta",
      postal_code: "12190",
      country: "Indonesia",
    },
    order_items: [
      {
        product_id: "PROD001",
        product_name: "Laptop Gaming ASUS ROG",
        quantity: 1,
        unit_price: 15000000,
        subtotal: 15000000,
        specifications_ordered: {
          processor: "Intel Core i7-12700H",
          ram: "16GB DDR4",
          color: "Black",
        },
      },
      {
        product_id: "PROD005",
        product_name: "Kopi Arabica Premium Toraja",
        quantity: 3,
        unit_price: 150000,
        subtotal: 450000,
        specifications_ordered: {
          weight: "200g",
          roast_level: "Medium",
        },
      },
    ],
    order_summary: {
      subtotal: 15450000,
      shipping_cost: 50000,
      tax: 1545000,
      total_amount: 17045000,
    },
    payment_info: {
      method: "Credit Card",
      status: "Paid",
      transaction_id: "TXN001",
      paid_at: new Date("2024-03-01T10:30:00Z"),
    },
    order_status: "Shipped",
    tracking_number: "TRK001",
    order_date: new Date("2024-03-01T10:00:00Z"),
    shipped_date: new Date("2024-03-02T14:00:00Z"),
    delivery_date: null,
    notes: "Pengiriman ekspres",
  },
  {
    _id: ObjectId("60a7c9c9c9c9c9c9c9c9c9c2"),
    order_id: "ORD002",
    customer_info: {
      customer_id: "CUST002",
      name: "Siti Nurhaliza",
      email: "siti.nurhaliza@email.com",
      phone: "082345678901",
    },
    shipping_address: {
      street: "Jl. Malioboro No. 45",
      city: "Yogyakarta",
      province: "DIY",
      postal_code: "55271",
      country: "Indonesia",
    },
    order_items: [
      {
        product_id: "PROD002",
        product_name: "iPhone 15 Pro Max",
        quantity: 1,
        unit_price: 18000000,
        subtotal: 18000000,
        specifications_ordered: {
          storage: "256GB",
          color: "Titanium Blue",
        },
      },
    ],
    order_summary: {
      subtotal: 18000000,
      shipping_cost: 25000,
      tax: 1800000,
      total_amount: 19825000,
    },
    payment_info: {
      method: "Bank Transfer",
      status: "Paid",
      transaction_id: "TXN002",
      paid_at: new Date("2024-03-05T09:15:00Z"),
    },
    order_status: "Delivered",
    tracking_number: "TRK002",
    order_date: new Date("2024-03-05T09:00:00Z"),
    shipped_date: new Date("2024-03-06T11:00:00Z"),
    delivery_date: new Date("2024-03-08T16:30:00Z"),
    notes: "Pelanggan VIP",
  },
  {
    _id: ObjectId("60a7c9c9c9c9c9c9c9c9c9c3"),
    order_id: "ORD003",
    customer_info: {
      customer_id: "CUST003",
      name: "Budi Santoso",
      email: "budi.santoso@email.com",
      phone: "083456789012",
    },
    shipping_address: {
      street: "Jl. Diponegoro No. 78",
      city: "Surabaya",
      province: "Jawa Timur",
      postal_code: "60241",
      country: "Indonesia",
    },
    order_items: [
      {
        product_id: "PROD003",
        product_name: "Nike Air Jordan 1 Retro High",
        quantity: 2,
        unit_price: 2500000,
        subtotal: 5000000,
        specifications_ordered: {
          color: "Bred (Black/Red)",
          size: "42",
        },
      },
      {
        product_id: "PROD005",
        product_name: "Kopi Arabica Premium Toraja",
        quantity: 5,
        unit_price: 150000,
        subtotal: 750000,
        specifications_ordered: {
          weight: "200g",
          roast_level: "Medium",
        },
      },
    ],
    order_summary: {
      subtotal: 5750000,
      shipping_cost: 30000,
      tax: 575000,
      total_amount: 6355000,
    },
    payment_info: {
      method: "E-Wallet",
      status: "Paid",
      transaction_id: "TXN003",
      paid_at: new Date("2024-03-10T14:20:00Z"),
    },
    order_status: "Processing",
    tracking_number: null,
    order_date: new Date("2024-03-10T14:00:00Z"),
    shipped_date: null,
    delivery_date: null,
    notes: "Pesanan ganda untuk toko",
  },
  {
    _id: ObjectId("60a7c9c9c9c9c9c9c9c9c9c4"),
    order_id: "ORD004",
    customer_info: {
      customer_id: "CUST004",
      name: "Maya Putri",
      email: "maya.putri@email.com",
      phone: "084567890123",
    },
    shipping_address: {
      street: "Jl. Asia Afrika No. 90",
      city: "Bandung",
      province: "Jawa Barat",
      postal_code: "40112",
      country: "Indonesia",
    },
    order_items: [
      {
        product_id: "PROD004",
        product_name: "Samsung 55 inch QLED TV",
        quantity: 1,
        unit_price: 12000000,
        subtotal: 12000000,
        specifications_ordered: {
          screen_size: "55 inch",
          color: "Carbon Silver",
        },
      },
    ],
    order_summary: {
      subtotal: 12000000,
      shipping_cost: 100000,
      tax: 1200000,
      total_amount: 13300000,
    },
    payment_info: {
      method: "Installment",
      status: "Pending",
      transaction_id: "TXN004",
      paid_at: null,
    },
    order_status: "Pending Payment",
    tracking_number: null,
    order_date: new Date("2024-03-12T11:45:00Z"),
    shipped_date: null,
    delivery_date: null,
    notes: "Pembayaran cicilan 12x",
  },
  {
    _id: ObjectId("60a7c9c9c9c9c9c9c9c9c9c5"),
    order_id: "ORD005",
    customer_info: {
      customer_id: "CUST005",
      name: "Dedi Kurniawan",
      email: "dedi.kurniawan@email.com",
      phone: "085678901234",
    },
    shipping_address: {
      street: "Jl. Gajah Mada No. 156",
      city: "Medan",
      province: "Sumatera Utara",
      postal_code: "20212",
      country: "Indonesia",
    },
    order_items: [
      {
        product_id: "PROD001",
        product_name: "Laptop Gaming ASUS ROG",
        quantity: 1,
        unit_price: 15000000,
        subtotal: 15000000,
        specifications_ordered: {
          processor: "Intel Core i7-12700H",
          ram: "16GB DDR4",
          color: "Black",
        },
      },
      {
        product_id: "PROD003",
        product_name: "Nike Air Jordan 1 Retro High",
        quantity: 1,
        unit_price: 2500000,
        subtotal: 2500000,
        specifications_ordered: {
          color: "Bred (Black/Red)",
          size: "43",
        },
      },
    ],
    order_summary: {
      subtotal: 17500000,
      shipping_cost: 75000,
      tax: 1750000,
      total_amount: 19325000,
    },
    payment_info: {
      method: "Cash on Delivery",
      status: "Pending",
      transaction_id: "TXN005",
      paid_at: null,
    },
    order_status: "Confirmed",
    tracking_number: "TRK005",
    order_date: new Date("2024-03-15T13:30:00Z"),
    shipped_date: new Date("2024-03-16T10:00:00Z"),
    delivery_date: null,
    notes: "COD - Bayar di tempat",
  },
]);

db.orders.find();
